name: Run Pytest with GCC

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pytest:
    name: Pytest Checks (with GCC)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Ensure GCC is available
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        gcc --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build runtime library
      run: python src/main.py buildlib

    - name: Run tests
      run: |
        pytest
